name: Deploy to GitHub Pages

on:
  push:
    branches:
      - deploy

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Restore Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .next/cache
            node_modules/.cache
          key: build-${{ hashFiles('**/package-lock.json') }}-
          restore-keys: |
            build-${{ hashFiles('**/package-lock.json') }}-
          enableCrossOsArchive: true

      - name: Build project
        run: npm run build

      - name: Save Cache
        uses: actions/cache/save@v4
        with:
          path: |
            .next/cache
            .turbo/cache
            node_modules/.cache
          key: build-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('node_modules/.cache') }}
          enableCrossOsArchive: true

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
